# SonarCloud configuration for BiblioTech
sonar.organization=blycke
sonar.projectKey=blycke_bts-sio-slam-seance
sonar.sources=app,config,routes,resources/lang,resources/views
sonar.tests=tests
sonar.php.coverage.reportPaths=storage/coverage.xml
sonar.language=php
sonar.php.version=8.2
sonar.exclusions=vendor/**,storage/**,node_modules/**
sonar.login=${{ secrets.SONAR_TOKEN }}
