name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy script
        env:
          ENV: production
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh production
